### ISSUE TITLE
Builtin entity identification should not rely on label during validation

### ISSUE THREAD

**Issue by ClemDoum** [snipsco/snips-nlu#417]
When we validate and format the dataset we don't validate the builtin entities.
However builtin entities are identified by their label.

Internally we can identify them by label but when coming from the external we should not rely on the label.

If someone calls it's entity `snips/number` -> it's entity will be considered as builtin

**Comment by adrienball** [comment]
Follow up on this issue: I'm not sure we want to handle multiple entities having the same name but different types. So I'd rather keep relying on the entity name to detect its type.
WDYT @ClemDoum ?

**Comment by adrienball** [comment]
Closing this, as we have moved forward with the current behavior which is to keep relying on the entity name to detect if it is a builtin entity.
