### ISSUE TITLE
pip install snips-nlu fails if Rust compiler is not installed

### ISSUE THREAD

**Issue by jcoder58** [snipsco/snips-nlu#530]
I checked both the ReadMe and the documentation and didn't see a requirement for Rust.  However, when I try pip install snips-nlu, it fails twice, first:

    ModuleNotFoundError: No module named 'setuptools_rust'

I then ran pip install setuptools_rust, which worked and re-ran the original install and got:

    error: Can not find Rust compiler

    ----------------------------------------
    Command "c:\python36\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\___\\AppData\\Local\\Temp\\pip-build-5mnnvl6u\\snips-nlu-utils\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\JDW\AppData\Local\Temp\pip-kqplj12v-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\___\AppData\Local\Temp\pip-build-5mnnvl6u\snips-nlu-utils\

**Comment by ClemDoum** [comment]
Hi @jcoder58 what is your OS?

**Comment by jcoder58** [comment]
Sorry, forgot to include all of that:

Windows 10 64-bit
Python 3.6

**Comment by ClemDoum** [comment]
We currently have pre-built binaries (wheels) for `snips-nlu` and its dependencies for MacOS and Linux x86_64. If you use a different architecture/os you will need to build these dependencies from sources which means you will need to install [setuptools_rust](https://github.com/PyO3/setuptools-rust) and [Rust](https://www.rust-lang.org/en-US/install.html) before running the `pip install snips-nlu` command.

**Comment by ClemDoum** [comment]
Let's me know if you have trouble building the lib ;)
