### ISSUE TITLE
Contribute support for Serbian language

### ISSUE THREAD

**Issue by dekstroza** [snipsco/snips-nlu#561]
Hi there, thank you for sharing your work as open source!

I would like to try and add support for Serbian language and contribute it in the process, would you be willing to accept contribution, perhaps give me few pointers on where and how to start?
Regards,
Dejan

**Comment by ClemDoum** [comment]
Hi @dekstroza,

Thanks for your question. To integrate languages I gave a few pointers here: https://github.com/snipsco/snips-nlu/issues/527.

Unfortunately neither [Rustling](https://github.com/snipsco/rustling-ontology) nor [Duckling](https://github.com/facebook/duckling) support Serbian for now (I'm sure for Rustling, not entirely for Duckling so please double check), so you'll get stuck with builtin-entities quite quickly I think.

**Comment by dekstroza** [comment]
Hi @ClemDoum,

Thanks for quick response and pointers. Snips-nlu is based on Rustling (unless I got it wrong), I 'll tackle Rustling first, and then come back here. Would you still be interested in taking contribution if I manage to get support in Rustling first?

**Comment by adrienball** [comment]
Hi @dekstroza,
Snips NLU is indeed based on [Rustling](https://github.com/snipsco/rustling-ontology) and we'd be very interested in taking contribution to Rustling to support new languages. If you manage to add minimal support for Serbian we will make our best to propagate it to snips-nlu-ontology and finally to snips-nlu.
We haven't had the time yet to write some documentation about adding new languages, but it is on our radar.
Don't hesitate to ping us if you struggle at some point, thanks a lot ;)
Cheers

**Comment by dekstroza** [comment]
Hi, I have pretty crude version (for now), for sr language in rustling-ontology, should i create pull request there to track it? It's pretty basic at this point, grammar for sr, data translations for training in sr language etc...I am pretty new to all this, so please be gentle, I might be completely missing the elephant in the room :)
Cheers,
Dejan

**Comment by adrienball** [comment]
Hi, that's great! 
Yes, the way to go is to create a pull request on rustling-ontology, from which we will see how we move forward 🙂

**Comment by ClemDoum** [comment]
Closing this one as question has been answered
