### ISSUE TITLE
Python 2 support timeframe

### ISSUE THREAD

**Issue by antontarasenko** [snipsco/snips-nlu#564]
Some packages, like NumPy, announced dropping Python 2 support in upcoming releases.

What about Snips NLU? For how long do you, guys, plan to maintain compatibility with Python 2.7?

**Comment by adrienball** [comment]
Hi @antontarasenko ,
It is not completely clear at the moment, but I think we will try to maintain compatibility until [Python 2.7 retires in 2020](https://www.python.org/dev/peps/pep-0373/). After that it is likely that we stop all efforts to maintain compatibility, but it really depends on how things go in terms of adoption by the community.

Just out of curiosity, may I ask what is your use case ? 
Cheers
