### ISSUE TITLE
Performance Issues

### ISSUE THREAD

**Issue by walpoletim-bjss** [snipsco/snips-nlu#590]
We have a model with 244 intents

When running against a trained model on an Mac pro (16Gb), it takes over 30 seconds to run a purse a query against the engine.

**Comment by adrienball** [comment]
Hi @walpoletim-bjss ,
I need a bit more of context to help you on this.

What is the average length of your intent utterances in terms of number of words ?
What is the average number of entities per utterance ?
How much time takes the training?

Thanks!

**Comment by walpoletim-bjss** [comment]
Hi - Have refactored the code, and now int responding as expected.
Will continue testing
