### ISSUE TITLE
KeyError: 'snips/number'

### ISSUE THREAD

**Issue by deepankar27** [snipsco/snips-nlu#598]
Hello Team & @adrienball 

I am have created dataset like this:

```
"getInfoFrDoc": {
      "utterances": [  
        {
          "data": [
            {
              "text": "how to get doc in "
            },
            {
              "text": "2",
              "entity": "snips/number",
              "slot_name": "numofDays"
            },
            {
              "text": " days?"
            }
          ]
        }
      ]
    }
```

While training I am getting exception KeyError: 'snips/number' & if I change the snips/number to snips/datetime then it creates the model.

Trace:
```
debug:
chunk: {'text': '?'}
--###--
--##--
chunk: {'text': 'how to get document in '}
--###--
--##--
chunk: {'text': '2', 'entity': 'snips/number', 'slot_name': 'numofDays'}
--###--

Traceback (most recent call last):
  File "test_snips.py", line 14, in <module>
    nlu_engine.fit(sample_dataset)
  File "/home/admin/anaconda3/lib/python3.6/site-packages/snips_nlu/nlu_engine/nlu_engine.py", line 69, in fit
    dataset = validate_and_format_dataset(dataset)
  File "/home/admin/anaconda3/lib/python3.6/site-packages/snips_nlu/dataset.py", line 57, in validate_and_format_dataset
    queries_entities_values = extract_queries_entities(dataset)
  File "/home/admin/anaconda3/lib/python3.6/site-packages/snips_nlu/dataset.py", line 32, in extract_queries_entities
    entities_values[chunk[ENTITY]].append(chunk[TEXT])
KeyError: 'snips/number'
```
Can you please let me know where is the issue. I tried to debug the code but doesn't get any luck.

Thanks,
Deepankar

**Comment by adrienball** [comment]
Hi @deepankar27,
How did you create your dataset?

If you created it manually, then check that your json dataset has the three following keys at the root:
```
{
  "intents": {},
  "entities": {},
  "language": "en"
}
```

Alternatively, to avoid these troubles when creating your dataset, you can use the CLI tool as explained in the [tutorial section](http://snips-nlu.readthedocs.io/en/latest/tutorial.html#snips-dataset-format) of the documentation

**Comment by deepankar27** [comment]
@adrienball Awesome..!! Just added `snips/number` under `entities{}`  & worked like a charm. 
I guess in the Cloud percentage is not working. I tried to set percentage but it didn't yell until I change it to number/ordinal. I will share the data tomorrow.

**Comment by adrienball** [comment]
Hey @deepankar27, I'm closing this issue as it's been two weeks since your last update.
Feel free to open another one if you have any trouble.
Cheers

**Comment by deepankar27** [comment]
@adrienball Sorry for the late reply but thanks a lot!!
