### ISSUE TITLE
error loading a saved engine

### ISSUE THREAD

**Issue by hvaneylen** [snipsco/snips-nlu#625]
I did the tutorial and save the engine state.
When I try to load it - I obtain 
...
snips_nlu.resources.MissingResource: Language resource 'en' not found. This may be solved by running 'snips-nlu download en'

But the resource language has been found for the saving done just before with this code
snips.load_resources('snips_nlu_en') <-- this works
but not with this code 
load_resources(u"en")
During the language installation I have this message 
Creating a shortcut link for 'snips_nlu_en' didn't work, but you can still load the resources via its full package name: snips_nlu.load_resources('snips_nlu_en')

I guess that the loading engine code use the second instruction to load the resource.

How can I solve this problem - I need to be able to save / load trained engines.

Thanks

**Comment by adrienball** [comment]
From your logs, there was an issue when creating the symbolic link for the downloaded resources. You can try fixing the link by running:
```
snips-nlu link snips_nlu_en en --force
```

If it works successfully, you will be able to load resources with `load_resources(u"en")`.
Otherwise, you can just keep `load_resources(u"snips_nlu_en")`, i.e. loading the resources using the full package name instead of the linked shortcut.

**Comment by hvaneylen** [comment]
Ok that's work but I need to run the anaconda prompt in administrator mode.

Thx

________________________________
De : Adrien Ball <notifications@github.com>
Envoyé : samedi 14 juillet 2018 13:39:26
À : snipsco/snips-nlu
Cc : Hugues Van Eylen; Author
Objet : Re: [snipsco/snips-nlu] error loading a saved engine (#625)


From your logs, there was an issue when creating the symbolic link for the downloaded resources. You can try fixing the link by running:

snips-nlu link snips_nlu_en en --force


If it works successfully, you will be able to load resources with load_resources(u"en").
Otherwise, you can just keep load_resources(u"snips_nlu_en"), i.e. loading the resources using the full package name instead of the linked shortcut.

**Comment by adrienball** [comment]
Are your running within a virtual environment?
Admin mode is usually required when you're not in a virtual env.

**Comment by adrienball** [comment]
I'm closing this as it's been 7 days, feel free to reopen if you still have troubles.

**Comment by waterflyer** [comment]
Hey, I'm hitting the same issue which is linking failed, so I tried the method @adrienball mentioned on Jul 14, 2018, and then I got the following issue:
OSError: symbolic link privilege not held
I'm using windows 10 and working at virtual environment on Pycharm. 
How could I solve this problem? 
Thank you.

**Comment by hvaneylen** [comment]
Have you run this "snips-nlu link snips_nlu_en en --force" in administrator mode ? otherwise It didn't work for me.

**Comment by waterflyer** [comment]
@hvaneylen Thank you, you are correct. I did run the installation process on admin mode and guess what, all good and installed successfully without any more works.
