### ISSUE TITLE
parsing of decimals values lead in float resolution

### ISSUE THREAD

**Issue by McFoggy** [snipsco/snips-nlu#636]
from time to time, some decimals number are parsed as if they were computed requiring some post processing.
In my case after NLU processing I present again the data to the end user and thus I do not want to show them `12.699999809265137` but `12.7`.

Are there some options to control this behavior, is it a bug or a _feature_?

```
{
    "input": "donnée d'entrée 12,7",
    "intent": {
        "intentName": "bloodPressureCombined",
        "probability": 1
    },
    "slots": [
        {
            "range": {
                "start": 17,
                "end": 21
            },
            "rawValue": "12,7",
            "value": {
                "kind": "Number",
                "value": 12.699999809265137
            },
            "entity": "snips/number",
            "slotName": "data"
        }
    ]
}
```

**Comment by McFoggy** [comment]
hum somehow it is linked to the representation of floats in python:

```
>>> format(12.7, '.12g')
'12.7'
>>> format(12.7, '.24g')
'12.6999999999999992894573'
```

the results above might depend also on the python version/computer arch/....

Any hint to find a way to stabilize that number/decimal/float transcription? I am currently using standard json module via : `json.dumps(result, indent=2)`

**Comment by adrienball** [comment]
Hey @McFoggy, you may want to check this thread --> https://stackoverflow.com/questions/1447287/format-floats-with-standard-json-module

**Comment by McFoggy** [comment]
Hi @adrienball thanks for the hint but unfortunately this does not suit exactly the need because I cannot arbitrarily truncate/round the numbers to some predefined number of decimals. This has to be dynamically done based on the raw input and thus the 'converter' needs to know the intent/slot and cannot work at the float value level.
Currently I do this in the consumer part _(a client side javascript app)_ as I am a bit newbie in Python to be able to do it in the simple flask REST API I have built to expose the intents.

I fully understand it is not a [snips-nlu](https://github.com/snipsco/snips-nlu) issue (and thus I close it) but I am sure that others than me also expose the intent results via REST ; so perhaps someone had some info on how to dump the json in a more correct/"intent meaningful" way.
