### ISSUE TITLE
Can't install en model in python3

### ISSUE THREAD

**Issue by HarshitDaftary** [snipsco/snips-nlu#646]
For below command I am unable to install the en model.

$ python3 -m snips_nlu download en --user
$ python3 -m snips_nlu download en
$ snips-nlu download en

Resources compatibility error
No compatible resources found for version 0.16.2

**Comment by adrienball** [comment]
Hey @HarshitDaftary @akhilvasvani ,
Indeed, the compatibility file was not updated, it is done now.
Cheers

**Comment by akhilvasvani** [comment]
Thanks @adrienball
