### ISSUE TITLE
Tools for generating dataset

### ISSUE THREAD

**Issue by djKooks** [snipsco/snips-nlu#652]
Hello
I'm first in this project. Thanks to know!
Is there a some kind of tool to generate dataset like `sample_dataset.json`? Because it can be compleated when It becomes big...

Thanks.

**Comment by adrienball** [comment]
Hey @djKooks ,
There is indeed a command line interface to generate a dataset from friendly text files, check [this section](https://snips-nlu.readthedocs.io/en/latest/tutorial.html#snips-dataset-format) of the documentation to know more about it.
Cheers,
Adrien

**Comment by djKooks** [comment]
@adrienball thanks for reply! Where can I find a guide about CLI?

**Comment by adrienball** [comment]
@djKooks Have you read the section of documentation that I mentioned in my previous comment ? Everything is explained there 😉

**Comment by djKooks** [comment]
@adrienball oh, sorry. I couldn't find cli guide in the bottom.
Thanks for the guide!

One more, is there a way to generate by other file, like csv or xls? Because I think someone could want to make a format using excel(spreadsheet)...

**Comment by YuukanOO** [comment]
Hi @djKooks, I have developed something similar to chatito (as linked in the docs) since it doesn't fit all my needs to ease the process of defining training data. Maybe it can help you https://github.com/atlassistant/chatl

**Comment by adrienball** [comment]
Closing this issue as it seems resolved.
