### ISSUE TITLE
Cannot install :  No module named 'setuptools_rust

### ISSUE THREAD

**Issue by yellowiscool** [snipsco/snips-nlu#664]
How to reproduce :

```sh
docker run -it --rm python pip install snips-nlu
```

**Comment by adrienball** [comment]
Hi @yellowiscool ,
We have pre-built wheels for various architectures and python versions, but for the rest the `pip install snips-nlu` command will install the package from source distribution. In this case, `rust` and the `setuptools_rust` python package must be installed beforehand.

Note that this can happen if, for instance, you are running Python 3.7, as it is not officially supported yet and therefore we haven't published wheels for this version yet.

**Comment by yellowiscool** [comment]
Thanks for your answer. I tried the following command with success :

```
docker run -it --rm python:3.4 pip install snips-nlu
```

Maybe it could be put somewhere in the README that Python 3.7 is not officially supported yet and that prebuilt packages are not available for all python versions on linux x86_64.

**Comment by adrienball** [comment]
Closing this issue, as it is now specified in the README that Python3.7 is not supported yet #665 .

**Comment by DoumanAsh** [comment]
@adrienball Sorry to bother, but is there tracking issue or what sort of issues prevent 3.7 from support 
/me doesn't want to have multiple copies of python on machine
