### ISSUE TITLE
cannot install snips-nlu on raspberry pi

### ISSUE THREAD

**Issue by alice-assistant** [snipsco/snips-nlu#675]
snips-nlu always seems to fail while using pip install snips-nlu on a raspberry pi. I have installed rust and it is working. I either get a rust compiler error or a cargo error. 

`error: cargo failed with code: 101`
it seems to install all other libraries fine but it cannot install these two packages (snips-nlu-ontology and snips-nlu-utils)

**Comment by adrienball** [comment]
I'm closing this as it has been answered in this thread --> https://forum.snips.ai/t/cannot-install-snips-nlu-on-raspberry-pi-3b/318

Cheers

**Comment by adrienball** [comment]
I'm closing this as it has been answered in this thread --> https://forum.snips.ai/t/cannot-install-snips-nlu-on-raspberry-pi-3b/318

Cheers
