### ISSUE TITLE
German NLU Time bug

### ISSUE THREAD

**Issue by maxbachmann** [snipsco/snips-nlu#689]
The german nlu has a bug with the time: In english 9-10 o'clock results in 9:00-10:00 In German 9-10 Uhr results in 9:00-11:00

I added a few screenshots to show the problem

![screenshot_20180903_1300](https://user-images.githubusercontent.com/44199644/47525764-5bb7ba80-d89e-11e8-8408-2402eb55d988.png)
![screenshot_20180903_131629](https://user-images.githubusercontent.com/44199644/47525767-5ce8e780-d89e-11e8-8375-9756051fa4c8.png)
![screenshot_20180903_130318](https://user-images.githubusercontent.com/44199644/47525771-5eb2ab00-d89e-11e8-8584-d2f387dfcfce.png)

**Comment by adrienball** [comment]
Hi @maxbachmann,
Thanks for reporting, I've put this on our backlog.
Best,
Adrien

**Comment by rosastern** [comment]
Fixed in rustling-ontology 0.18.0
