### ISSUE TITLE
Being able to comment entity and intent input lines

### ISSUE THREAD

**Issue by joffreyvillard** [snipsco/snips-nlu#690]
Hi,

Here is a feature request for the AssistantDataset class!
When using the flat input text files (intent_xxx and entity_xxx), I found it would be pretty useful to be able to comment a line (either an entity value or a training sentence) by e.g. adding a simple "#" at the beginning of this line.

Best,
Joffrey

**Comment by adrienball** [comment]
Hi @joffreyvillard ,
Interesting request indeed, that makes sense. However, it cannot be directly implemented the way you suggest as it would conflict with https://github.com/snipsco/snips-nlu/pull/633
This raises questions regarding the current formats used to represent a dataset. The [JSON format](https://github.com/snipsco/snips-nlu/blob/develop/sample_datasets/flights_dataset.json) is great, but the other format using the [text files](https://github.com/snipsco/snips-nlu/tree/develop/snips_nlu/cli/dataset/examples) is not very satisfying in my opinion.
We are currently investigation other user friendly formats. YAML could be an interesting candidate.

I'll let this issue open, and will try to work on a better format soon.
Thanks!

**Comment by joffreyvillard** [comment]
Hi @adrienball 
Thanks for your reply, I see. As first proxy, we could use ";" for comments as well. 
Would not need to wait for a new format to be defined and implemented.

> The JSON format is great, but the other format using the text files is not very satisfying in my opinion.

The text files are far better for trainers that work on improving NLP without entering all the technicalities behind. The markdown-like syntax is very simple and intuitive IMO.

**Comment by adrienball** [comment]
I'm closing this issue as it has been addressed with the new [YAML format](https://snips-nlu.readthedocs.io/en/latest/dataset.html#yaml-format) introduced in release `0.18.0`.
