### ISSUE TITLE
Syntax Error while creating a dataset in ubuntu

### ISSUE THREAD

**Issue by pandeysudhanshu** [snipsco/snips-nlu#698]
snips-nlu generate-dataset en intent_turnLightOn.txt intent_turnLightOff.txt intent_setTemperature.txt entity_room.txt > dataset.json
  File "<ipython-input-1-da00410dfad3>", line 1
    snips-nlu generate-dataset en intent_turnLightOn.txt intent_turnLightOff.txt intent_setTemperature.txt entity_room.txt > dataset.json
                     ^
SyntaxError: invalid syntax

**Comment by pandeysudhanshu** [comment]
I tried this code but every time I get this error.I tried in Python3.5 but the error is still the same.

**Comment by adrienball** [comment]
Hi @pandeysudhanshu ,

> snips-nlu generate-dataset en intent_turnLightOn.txt intent_turnLightOff.txt intent_setTemperature.txt entity_room.txt > dataset.json

This must be run from the command line in a terminal, it is not Python code. Before running that, you must install `snips-nlu` using `pip install snips-nlu`.

Best,
Adrien
