### ISSUE TITLE
Question regarding slot_filler feature_factory.py

### ISSUE THREAD

**Issue by gembin** [snipsco/snips-nlu#722]
I got one question regarding the return line of the following code, correct me if i'm wrong.
https://github.com/snipsco/snips-nlu/blob/develop/snips_nlu/slot_filler/feature_factory.py#L553-L562

```python
            for ent in builtin_entities:
                entity_start = ent[RES_MATCH_RANGE][START]
                entity_end = ent[RES_MATCH_RANGE][END]
                indexes = []
                for index, token in enumerate(tokens):
                    if (entity_start <= token.start < entity_end) \
                            and (entity_start < token.end <= entity_end):
                        indexes.append(index)
            return get_scheme_prefix(token_index, indexes,  # <-- this line after outer for loop
                                         self.tagging_scheme)
```
Per my understanding the  `return get_scheme_prefix(...)` should after the outer `for` loop as shown above.

**Comment by adrienball** [comment]
Hi @gembin ,
The code is a bit confusing here I agree. However, the code is correct as is.
The outer `for` loop could be replaced by:

```python
if builtin_entities:
    ent = builtin_entities[0]
    entity_start = ent[RES_MATCH_RANGE][START]
    entity_end = ent[RES_MATCH_RANGE][END]
    ...
else:
   return None
```

The idea is that we look for builtin entities, of type `builtin_entity`, that overlap with the current token index:
```python
builtin_entities = builtin_entity_parser.parse(
                text, scope=[builtin_entity], use_cache=True)
builtin_entities = [ent for ent in builtin_entities
                              if entity_filter(ent, start, end)]
```
In most cases there will be 0 or 1 entity. In case where there are more, as it is not very clear what to do, we fallback to the first one.

**Comment by gembin** [comment]
Thanks @adrienball , yes, it's a bit confusing here.
It will be more readable if replaced as above with some comments to explain the idea : -).
