### ISSUE TITLE
Incremental Training

### ISSUE THREAD

**Issue by timtutt** [snipsco/snips-nlu#770]
Is it possible to do incremental training? I build training sets that have between 10-20K training examples and training takes a long time. Would like to be able to add a new training example to a model incrementally without having to wait for hours to retrain the set. Are there any thoughts on how to approach this?

**Comment by ClemDoum** [comment]
Hi @timtutt,

Can you run the training with in verbose mode (either with the `-v` flag if you run it from the CLI or with the `snips-nlu` logger in debug mode) ?

That would help me understand if it's intent classification or slot filling that takes most of the computation time. My guess is that it's the slot filling part which is the longest (sadly it's not easy to make this part faster).  In any case incremental retraining for both part seems complicated to implement since the underlying models don't support incremental training out of the box.

If you want to speed up intent classification part, you can try using a Naive Bayes classifier instead of the SGDClassifier, i think this classifier would train much faster (but there a little bit of work required).

For me your number 1 options is to run metrics in with the `snips-nlu cross-val-metrics` or `snips-nlu train-test-metrics` to make sure that you need all the data. Most assistant have less than 10k (or way less) than 10k utterances and have very good performances.
What you could do is to reduce the size of your training dataset and see if still get the same NLU performances.

**Comment by ClemDoum** [comment]
That said, if you don't need to retrain the whole assistant you can implement some advanced training strategy.

The training of the NLU mostly works the following way:
1. train an intent classifier that will distinguish between each
2. train one slot filler for each intent

If after running the `cross-val-metrics` on your 20k utterances you discover that you have average intent classification performances (you might want to add more data the intent classification part), excellent slot filling performances for most intents (you don't want to add more data for these slots fillers) and poor slot filling performances on 2 intents (you want to add more data for these 2 slots fillers).

What you could do is:
1. Build a new dataset with more data
2. Retrain the intent classification to improve it
3. Retrain only the 2 bad slot fillers

Depending on the output of you metrics I can detail you this strategy

**Comment by timtutt** [comment]
@ClemDoum  - Thanks much for the response... I know the issue appears to be the slot filling. Intent does very well on low amounts of training data. The problem is there are so many possible values and combinations of slots it appears to get that wrong with lower amounts of training data.

I'll try running in verbose mode to get you more specific stats.

**Comment by timtutt** [comment]
Also - I'm using the programmatic api, not the commandline program to generate

**Comment by timtutt** [comment]
@ClemDoum - slot fillers are definitely my issue. I noticed something while looking at the logs - each intent has a slot filler and they all run sequentially. There are a couple that run longer than the others, but in general they all run at about the same amount of time. Is it possible to force these slot fillers to run in parallel when running `engine.fit`?

The second question I have is how would I go about re-training a specific slot filler with the programmatic api such that it updates the model that's already been trained?

**Comment by adrienball** [comment]
@timtutt 
Indeed for now the slot fillers are trained sequentially. We could indeed look at making the slot fillers trainings parallel using the joblib python library.

Regarding your second question, you can definitely retrain a specific component of the pipeline like a slot filler:

```python
import io
import json

from snips_nlu import SnipsNLUEngine

with io.open("path/to/dataset.json") as f:
    dataset = json.load(f)

engine = SnipsNLUEngine().fit(dataset)

# Make some update to the intent "my_intent" in the dataset
# ...

# The probabilistic parser is the second parser if you use the default config
proba_parser = engine.intent_parsers[1]
proba_parser.slot_fillers["my_intent"].fit(dataset, "my_intent")
```

Note that this will only affect the slot filling, and not the intent classification. If you want to retrain the intent classifier as well, then you can run:

```python
proba_parser.intent_classifier.fit(dataset)
```

I hope this helps.

**Comment by adrienball** [comment]
I realized that the code snippet above crashes when you run:

```python
proba_parser.slot_fillers["my_intent"].fit(dataset, "my_intent")
```

There is a small bug with resources that I'm going to fix. In the meantime, you can simply use the following (you need to add `from snips_nlu.slot_filler import CRFSlotFiller`):
```python
proba_parser.slot_fillers["my_intent"] = CRFSlotFiller().fit(dataset, "my_intent")
```

**Comment by timtutt** [comment]
@adrienball  - Thanks much for the response. This should fit my needs for now. Looking at current training times for the slot fillers this seems to be a pretty close alternative to the incremental training that I was looking for. Thanks much to you and @ClemDoum for providing the specifics on how to get here.

Would definitely be interested in the parallelization of the slot filling tasks as I feel this would dramatically increase training times. (My current slot fillers have an average training time of 5 minutes, but currently take 41 minutes to run sequentially with one of my smaller datasets).

Is this an area I can help with. Haven't spent much time in the code, but if you point me in the right direction I can take a stab at that.

**Comment by adrienball** [comment]
@timtutt - If you are interested in parallelizing the training of the slot fillers, then you should look at [this piece of code](https://github.com/snipsco/snips-nlu/blob/develop/snips_nlu/intent_parser/probabilistic_intent_parser.py#L80-L93) in the probabilistic intent parser `fit` method.
Here you can collect the intents that need training and use `joblib.Parallel`.
The way I see it is that parallelization should be configurable in the [`ProbabilisticIntentParserConfig`](https://github.com/snipsco/snips-nlu/blob/develop/snips_nlu/pipeline/configs/intent_parser.py#L10), for instance by adding an optional `parallel_jobs` parameter. You have access to the config in the `fit` method mentioned above.
Finally, the `CRFSlotFiller` object contains some C pointers so you won't be able to pass it directly to joblib. Instead you have to create it within each job.

I can definitely provides some help if you decide to move forward 🙂

**Comment by timtutt** [comment]
@adrienball  - By the way got a chance to test out the re-training of specific slot fillers. Worked like a charm. Thanks much for that. I'll go ahead and close out this issue as the core of my problem has been solved. Will spend sometime looking into mods for making the slot fillers run in parallel and provide a PR. 

Thanks again to both you and @ClemDoum. 

Cheers!
