### ISSUE TITLE
Yaml format, intent with "yes" or "no" in utterance crashes parsing

### ISSUE THREAD

**Issue by BertrandNOEL** [snipsco/snips-nlu#772]
Python 3.6.8
snips-nlu-0.19.4 snips-nlu-parsers-0.2.0 snips-nlu-utils-0.8.0

I define the following intent using yaml format
```yaml
type: intent
name: YesIntent
utterances:
  - yeah
  - sure
  - yes
  - yep
```
Trying to convert this yaml file to json, or trying to use it directly using
```bash
snips-nlu generate-dataset en dataset.yaml
```
or
```python
from snips_nlu.dataset import Dataset
dataset = Dataset.from_yaml_files("en", ['dataset.yaml'])
```
generates the following exception
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "xxx/venv/lib64/python3.6/site-packages/snips_nlu/dataset/dataset.py", line 163, in from_yaml_files
    intents_, entities_ = cls._load_dataset_parts(f, filename)
  File "xxx/venv/lib64/python3.6/site-packages/snips_nlu/dataset/dataset.py", line 177, in _load_dataset_parts
    intents.append(Intent.from_yaml(doc))
  File "xxx/venv/lib64/python3.6/site-packages/snips_nlu/dataset/intent.py", line 119, in from_yaml
    for u in yaml_dict["utterances"] if u.strip()]
  File "xxx/venv/lib64/python3.6/site-packages/snips_nlu/dataset/intent.py", line 119, in <listcomp>
    for u in yaml_dict["utterances"] if u.strip()]
AttributeError: 'bool' object has no attribute 'strip'
```

It is because the utterance "yes", is parsed by yaml library as a boolean

`yaml_dict["utterances"]` in https://github.com/snipsco/snips-nlu/blob/develop/snips_nlu/dataset/intent.py#L119 would print `['yeah', 'sure', True, 'yep']`

I don't know enough of that yaml library to know if it is possible to force reading as String. Will check.

**Comment by adrienball** [comment]
Hi @BertrandNOEL ,
You have to put yes between double quotes: ˋ"yes"`
YAML is a superset of JSON, with tries to be smarter. You can always fallback to json values when there is a conflict.

Cheers

**Comment by BertrandNOEL** [comment]
Thanks,
Yes of course I will put quotes.
I delegate this Yaml file to another team, and I hoped I would use it straight from them. Guess that I will have to do a pre-processing part
I'm closing this issue, but if anybody has a good idea on how to avoid doing this pre-processing part, don't hesitate to share
