### ISSUE TITLE
Parsing failure impossible to diagnose

### ISSUE THREAD

**Issue by Shotgun167** [snipsco/snips-nlu#794]
If you have a syntax error in a yaml training file, Snips will tell you something like:

Missing ending ']' in annotated utterance"

Good luck finding which utterance is missing that bracket.

I found that adding " + state.input" to the exception string in input.py/capture_slot and input.py/capture_tagged would print the utterance, so that the fix was quick.

**Comment by adrienball** [comment]
@Shotgun167 Thanks for reporting, the fix will be in the next release 0.19.7
