### ISSUE TITLE
Retrieving version

### ISSUE THREAD

**Issue by Shotgun167** [snipsco/snips-nlu#805]
Retrieving the Snips version is broken on my Mac, with Python 3.7

snips/$ snips-nlu --version
/usr/local/lib/python3.7/site-packages/sklearn/feature_extraction/text.py:17: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  from collections import Mapping, defaultdict

Unknown command: --version
Available: train, parse, download, download-all-languages, download-entity, download-language-entities, version, model-version, link, generate-dataset, cross-val-metrics, train-test-metrics

snips/$ snips-nlu version
/usr/local/lib/python3.7/site-packages/sklearn/feature_extraction/text.py:17: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  from collections import Mapping, defaultdict
0.19.5

**Comment by adrienball** [comment]
Hi @Shotgun167 ,
The correct command is indeed `snips-nlu version` and not `snips-nlu --version`.
The command works as it correctly prints the version (`0.19.5`). There is a warning originating from sklearn but that's all.

Here is how you can retrieve the snips-nlu version if you need to use it in python:
```python
from snips_nlu import __version__
print(__version__)
```

**Comment by adrienball** [comment]
BTW, you won't have this warning anymore if you upgrade `snips-nlu` to `0.19.6`.

**Comment by Shotgun167** [comment]
Thank you.  I see it now.
