### ISSUE TITLE
generate-dataset quote handling is OS dependant

### ISSUE THREAD

**Issue by Shotgun167** [snipsco/snips-nlu#809]
`snips-nlu generate-dataset en *.yaml > nebula_data.json`

The contents of nebula_data.json will vary depending on the OS.  Quotes from the yaml files will be escaped on Macs ( `"My text" => "\"My text\""`), but not on Windows (`"My text" => "My text"`).

Also, Windows will not accept `*.yaml`.  My co-workers, who refuse to use a real operating system, have written a BAT file that looks like:

`snips-nlu generate-dataset en 1.yaml 2.yaml 3.yaml etc.yaml > nebula_data.json`

Yes.  I did cry when I saw that.         https://www.youtube.com/watch?v=j7OHG7tHrNM

[EDIT by maintainer: put examples in markdown code blocks for clarity]

**Comment by adrienball** [comment]
@Shotgun167 
Just to be sure I've understood correclty, the MacOs behavior is wrong while the Windows one is correct ?
Could you provide a small reproducible example? 

I can't reproduce on my machine (MacOS 10.14), but perhaps I have missed something. Here is what I have:

```console
$ cat test.yaml
---
type: intent
name: HelloWorld
utterances:
- Hello world
- 'Hello world'
- "Hello world"
$ snips-nlu generate-dataset en test.yaml > dataset.json
$ cat dataset.json
{
  "entities": {},
  "intents": {
    "HelloWorld": {
      "utterances": [
        {
          "data": [
            {
              "text": "Hello world"
            }
          ]
        },
        {
          "data": [
            {
              "text": "Hello world"
            }
          ]
        },
        {
          "data": [
            {
              "text": "Hello world"
            }
          ]
        }
      ]
    }
  },
  "language": "en"
}
```

Regarding the `*.yaml` thing, I'm afraid it is not really in our hand.

**Comment by adrienball** [comment]
I think I got confused because of github rendering your escaped quotes.
You should put your example in a code block so that `\` are not interpreted by github markdown renderer.

**Comment by Shotgun167** [comment]
I'm thinking that the Mac behavior should be considered correct.  If I put a quote inside the parenthesis of my training utterance, I would expect that quote to be included as part of the string in the generated json (Yes?  No?);  however, I think the bigger issue is that it behaves differently depending on OS.  

To work off of your example above:
<
---
type: intent
name: HelloWorld
utterances:
- Hello [target:my_words]("world")
>

For the Mac, the json generated would have:
<
"data": [
            {
              "text": "Hello"
            },
            {
              "entity": "my_words"
              "slot_name": "target"
              "text": "\"world\""
            }
          ]
>

Good enough.  The quotes are part of the slot.
But, on Windows, the following will be generated:
<
"data": [
            {
              "text": "Hello"
            },
            {
              "entity": "my_words"
              "slot_name": "target"
              "text": "world"
            }
          ]
>

The quotes got dropped from Windows json.  Comparing the results from the engines generated from the two datasets is now problematic.  I'd imagine this would only be an issue for shops that use multiple OSes.

**Comment by adrienball** [comment]
I can't reproduce this on Windows 10.
Here is what I have:

```console
(venv3) C:\Users\IEUser\dev\test>type test.yaml
---
type: intent
name: HelloWorld
utterances:
- Hello [target:my_words]("world")
(venv3) C:\Users\IEUser\dev\test>snips-nlu generate-dataset en test.yaml > dataset.json

(venv3) C:\Users\IEUser\dev\test>type dataset.json
{
  "entities": {
    "my_words": {
      "automatically_extensible": true,
      "data": [],
      "matching_strictness": 1.0,
      "use_synonyms": true
    }
  },
  "intents": {
    "HelloWorld": {
      "utterances": [
        {
          "data": [
            {
              "text": "Hello "
            },
            {
              "entity": "my_words",
              "slot_name": "target",
              "text": "\"world\""
            }
          ]
        }
      ]
    }
  },
  "language": "en"
}
```

Is there any intermediate processing of the yaml file in your pipeline which could somehow remove the escaping ?

**Comment by Shotgun167** [comment]
Hmm?  He is using Win Server 2016.  Windows has been moving towards more cross platform tolerance over the past few years, so this may only be a problem for older systems.  His workaround right now is to manually edit the JSON after the file is generated.
