### ISSUE TITLE
example of implicit entities with json format?

### ISSUE THREAD

**Issue by timtutt** [snipsco/snips-nlu#834]
I noticed in the documentation there is a way to assign an [implicit entity and slot](https://snips-nlu.readthedocs.io/en/latest/dataset.html?highlight=implicit#implicit-entity-values-and-slot-mapping) using the .yml format. Is this possible with the json format? If so, can you provide an example?

**Comment by adrienball** [comment]
Hi @timtutt ,
The [*Implicit entity values and slot mapping*](https://snips-nlu.readthedocs.io/en/latest/dataset.html?#implicit-entity-values-and-slot-mapping) feature is a YAML-only feature which is only there to make the task of annotating easier. Basically, it consists in reducing the amount of user-provided information to the strict minimum. 
For instance, if one utterance is labelled using `[my_slot:my_entity]` then we know that the slot `my_slot` corresponds to the entity `my_entity` and this mapping applies for all utterances so you can just use `[my_slot]` in all the other utterances.

So far we have made the choice of a strict format for the JSON dataset as it is not really supposed to be generated manually. Of course, this can evolve.

Can you share a bit your use case, or just simply how you would leverage this feature if it existed  ? 
Thanks!

**Comment by timtutt** [comment]
@adrienball  - thanks much for the response here. 

This was actually a misunderstanding on my part - I was under the assumption this feature would at run time impute and "extract" default/implicit entities for a given intent when those entities are not explicitly provided. 

Right now I handle this with business logic outside of snips... For example:

Example "When was the temperature the hottest?" or "What day was the hottest" and "What month was the temperature the hottest"

These all map to the same intent, but having snips automatically identify missing slots for that intent would be valuable. That said I've gotten around this by implementing in business logic.
