### ISSUE TITLE
datetime not recognized

### ISSUE THREAD

**Issue by flozi00** [snipsco/snips-nlu#865]
`---
type: intent
name: calendar_getevents
slots:
  - name: datetime
    entity: snips/datetime
    
utterances:
  - what appointments do i have on [datetime] (monday) ?
  - tell me my dates
  - tell me my dates for the [datetime] (next saturday)
  - tell me my appointments
  - tell me my timetable
  - what is on my calendar for [datetime] (today)
  - what is on my calendar for [datetime] (tomorrow)
  - what is on my calendar for [datetime] (sunday)
  - what is on my calendar [datetime] (today)
  - what is on my calendar [datetime] (next sunday)
  - whats on my calendar [datetime] (today)
  - whats on my calendar [datetime] (tomorrow)
  - whats on my calendar [datetime] (monday)
  - whats on my calendar [datetime] (tuesday)
  - whats on my calendar [datetime] (wednesday)
  - whats on my calendar [datetime] (thursday)
  - whats on my calendar [datetime] (friday)
  - whats on my calendar [datetime] (saturday)
  - whats on my calendar [datetime] (sunday)
  - whats on my calendar [datetime] (next week)
`
yaml file

`DATASET_PATH = Path(__file__).parent / "definition.json"
	with DATASET_PATH.open(encoding="utf8") as f:
	    sample_dataset = json.load(f)

	nlu_engine = SnipsNLUEngine(config=CONFIG_EN)
	nlu_engine.fit(sample_dataset)
	nlu_engine.persist(lang)`

training process

the datetime get not extracted, only the intention is returned

`{
  "input": "whats on my calendar for tomorrow",
  "intent": {
    "intentName": "calendar_getevents",
    "probability": 0.8726704018107356
  },
  "slots": []
}
`

**Comment by adrienball** [comment]
Hi @flozi00 ,
As mentioned in the [documentation](https://snips-nlu.readthedocs.io/en/latest/dataset.html#intent), the YAML format used to describe a labelled utterance is:

```find me a flight from [origin:city](Paris) to [destination:city](New York)```

There is no space between `]` and `(`.
Best
