### ISSUE TITLE
Fails to install on Python3.8

### ISSUE THREAD

**Issue by tnedev** [snipsco/snips-nlu#866]
**Describe the bug**
Under the description it says it works with Python>=3.5, however I have problems installing on Python3.8. With Python 3.6 3.7 install and works fine.
It looks like it's trying to build from source, because the first error is requiring setuptools-rust and then fails with not having a rust compiler.  

**Environment:**
 - OS: Linux/Ubuntu 
 - python version: 3.8
 - snips-nlu version: latest release

**Comment by adrienball** [comment]
Hi @tnedev ,
Indeed, wheels for Python3.8 were not available.
Besides, the version of scikit-learn that was used didn't have any python3.8 associated wheels on pypi.
I updated this dependency and made a new release (0.20.2), for which python3.8 wheels are now available.
Could you please upgrade to this version, and report if you still have any issue ?
Thanks

**Comment by tnedev** [comment]
Thanks for the quick response @adrienball 

I can confirm that it now works. However, python-crfsuite is failing and requiring to be build. 
After installing python3.8-dev, python-crfsuite builds ok along with snips-nlu 0.20.2

Thanks

**Comment by adrienball** [comment]
Just a note about the fact that the issue with `python-crfsuite` has been fixed in their latest release (see https://github.com/scrapinghub/python-crfsuite/issues/116).
