### ISSUE TITLE
After jan 2020

### ISSUE THREAD

**Issue by oziee** [snipsco/snips-nlu#871]
i see that this GitHub has a lot of work being put in.. what’s going to happen to this GitHub after jan 31 ?

**Comment by YuukanOO** [comment]
Got the same question. Will the core team continue its effort on this library?

**Comment by adrienball** [comment]
Hi @oziee , @YuukanOO ,
We understand that it may not be clear what is going to happen after Jan 31st given the fact that the Snips web Console will be closing at this date.
Many things are currently evolving on our side, following the Sonos acquisition.
As a result of this, we won't add new features to Snips NLU and no new languages will be added in the future. However, **we will keep a minimal support of the library and we will continue to provide bug fixes.**
Thanks
