### ISSUE TITLE
Even after install snips_nlu_en still get error Language resource 'en' not found.

### ISSUE THREAD

**Issue by apjunzhisheng** [snipsco/snips-nlu#882]
**Question**

I have install snips_nlu_en through python -m snips_nlu download en. And I get this.

Collecting snips_nlu_en==0.2.3
  Downloading https://github.com/snipsco/snips-nlu-language-resources/releases/download/snips_nlu_en-0.2.3/snips_nlu_en-0.2.3.
tar.gz (1.3 MB)
     |████████████████████████████████| 1.3 MB 2.2 MB/s
Building wheels for collected packages: snips-nlu-en
  Building wheel for snips-nlu-en (setup.py) ... done
  Created wheel for snips-nlu-en: filename=snips_nlu_en-0.2.3-py3-none-any.whl size=1297483 sha256=7869efca1ba1c074aad8a09058a
7ffcce7b3604b7bdf60dff59de058a386840c
  Stored in directory: C:\Users\JUNZHI~1.SHE\AppData\Local\Temp\pip-ephem-wheel-cache-81muznoo\wheels\f1\14\3e\eb8b6c087f01b71
8e64a3e373bfb1fb17190c025f2d6c2ea69
Successfully built snips-nlu-en
Installing collected packages: snips-nlu-en
Successfully installed snips-nlu-en-0.2.3

?[91mThe language resources were successfully downloaded, however linking failed.?[0m
Creating a shortcut link for 'en' didn't work: OSError('symbolic link privilege not held')

Then I try to use nlu_engine = nlu_engine.fit(sample_dataset), then I get error: 
Language resource 'en' not found. This may be solved by running 'python -m snips_nlu download en'

Please for helping me!
Thanks!

**Comment by adrienball** [comment]
This error `OSError('symbolic link privilege not held')` means that you are installing `snips-nlu` in a location where you do not have enough write permission. To avoid this issue, it is generally advised to work in a [virtual environment](https://virtualenv.pypa.io/en/latest/index.html).
