### ISSUE TITLE
Chatbots, Rust and FOSS version

### ISSUE THREAD

**Issue by philiprhoades** [snipsco/snips-nlu#889]
**Question**

I found your Medium article because I searched for the above subject - what will be the situation for using snips-nlu for my non-profit orgs now that you have been bought by Sonos?

Thanks,
Phil.

**Comment by adrienball** [comment]
Hi @philiprhoades ,
snips-nlu is distributed with an Apache 2.0 license (see the [license](https://github.com/snipsco/snips-nlu/blob/master/LICENSE)), which means that it can be used for any purpose (commercial use, distribution etc).
However, keep in mind that, as explained [here](https://github.com/snipsco/snips-nlu/issues/871#issuecomment-578068260), we provide a minimal support on this library (mostly bug fixes) and we won't add new features in the future.
Best
Adrien
